#!/usr/bin/env perl

use common::sense;

use constant USAGE => "Usage: astgen <rule-file>";

use DataGen::util;
use DataGen::gen_header_internal;
use DataGen::gen_header;
use DataGen::gen_source;

our $dataname;

my @vfuns = qw/destruct print/;

my $rules = do {
   my $file = $ARGV[0]
      or die USAGE;
   require $file
};

my $DATANAME = uc $dataname;

open my $nodes_h, ">", "include/${dataname}/gen/nodes.h"
   or die $!;
open my $internal_nodes_h, ">", "src/${dataname}/gen/nodes.h"
   or die $!;
open my $internal_kinds_h, ">", "src/${dataname}/gen/kinds.h"
   or die $!;

print "  ASTGEN  $ARGV[0]\n";

for my $file (sort keys %$rules) {
   print $nodes_h "#include <${dataname}/gen/$file.h>\n";
   print $internal_nodes_h "#include \"$file.h\"\n";
   print $internal_kinds_h "  ${DATANAME}_" . (uc $rules->{$file}[0]) . ",\n";
   gen_header_internal $file, @{ $rules->{$file} };
   gen_header          $file, @{ $rules->{$file} };
   DataGen::source::generate  $file, @{ $rules->{$file} };
}
