#include <ast.h>

#include "node.h"

#include "auto.h"
#include "break.h"
#include "case.h"
#include "const.h"
#include "continue.h"
#include "do.h"
#include "default.h"
#include "enumerator.h"
#include "extern.h"
#include "for.h"
#include "goto.h"
#include "if.h"
#include "label.h"
#include "register.h"
#include "return.h"
#include "static.h"
#include "switch.h"
#include "token.h"
#include "typedef.h"
#include "volatile.h"
#include "while.h"
